const mockMenu = [
  {
    id: '1',
    name: 'Margherita Pizza',
    price: 10.99, 
    delPrice: 2,
    category: 'Mains',
    rating: 4.5,
    description: 'A classic Italian pizza topped with fresh tomatoes, mozzarella, and basil.',
    preparationTime: '15-20 mins',
    deliveryCost: 'Delivery from £2',
    image: require('../assets/pizza1.jpg'),
    calories: 850,
    ingredients: 'Pizza dough, tomato sauce, fresh mozzarella cheese, fresh basil leaves, olive oil, salt.',
  },
  {
    id: '2',
    name: 'Cheeseburger',
    price: 8.99,
    delPrice: 1.50,
    category: 'Mains',
    rating: 4.2,
    description: 'A juicy beef patty topped with melted cheese, lettuce, and tomato.',
    preparationTime: '10-15 mins',
    deliveryCost: 'Delivery from £1.50',
    image: require('../assets/burger1.jpg'),
    calories: 300,
    ingredients: 'Burger bun, ground beef patty, cheese slice, lettuce, tomato, pickles, ketchup, mustard, salt, pepper.',
  },
  {
    id: '3',
    name: 'Caesar Salad',
    price: 7.99,
    delPrice: 1.20,
    category: 'Starters',
    rating: 4.0,
    description: 'Quick made salad with lots of vegetables plus sauce.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £1.20',
    image: require('../assets/salad2.jpg'),
    calories: 45,
    ingredients: 'Romaine lettuce, Caesar dressing, croutons, parmesan cheese, grilled chicken (optional), black pepper.',
  },
  {
    id: '4',
    name: 'Spaghetti Bolognese',
    price: 12.99,
    delPrice: 1.90,
    category: 'Mains',
    rating: 4.5,
    description: 'Freshly made spaghetti made with tomatoes and vegetables.',
    preparationTime: '20-25 mins',
    deliveryCost: 'Delivery from £1.90',
    image: require('../assets/spag1.jpg'),
    calories: 650,
    ingredients: 'Spaghetti, ground beef, tomatoes, onion, garlic, carrots, celery, olive oil, red wine (optional), salt, pepper, parmesan cheese (optional).',
  },
  {
    id: '5',
    name: 'Cheesy Pasta',
    price: 14.99,
    delPrice: 1.70,
    category: 'Mains',
    rating: 4.4,
    description: 'Special-made pasta hand-crafted with original cheese.',
    preparationTime: '30-45 mins',
    deliveryCost: 'Delivery from £1.70',
    image: require('../assets/pasta1.jpg'),
    calories: 130,
    ingredients: 'Pasta (penne, fusilli, or spaghetti), cheddar cheese, mozzarella cheese, cream, garlic, butter, parmesan cheese, salt, pepper, herbs (optional).',
  },
  {
    id: '6',
    name: 'Chicken Burrito',
    price: 9.50,
    delPrice: 2.50,
    category: 'Mains',
    rating: 4.3,
    description: 'A juicy chicken burrito made with spices and vegetables.',
    preparationTime: '15-35 mins',
    deliveryCost: 'Delivery from £2.50',
    image: require('../assets/burrito1.jpg'),
    calories: 420,
    ingredients: 'Flour tortilla, grilled chicken, rice, black beans, corn, lettuce, tomato, cheese, sour cream, salsa, guacamole (optional), cumin, chili powder, garlic, salt, pepper.',
  },
  {
    id: '7',
    name: 'Spicy Wings',
    price: 7.99,
    delPrice: 1.30,
    category: 'Starters',
    rating: 4.1,
    description: 'Chicken wings made with extra hot sauce and spices.',
    preparationTime: '10-12 mins',
    deliveryCost: 'Delivery from £1.30',
    image: require('../assets/wings1.jpg'),
    calories: 220,
    ingredients: 'Chicken wings, hot sauce, cayenne pepper, paprika, garlic powder, onion powder, salt, black pepper, olive oil, chili flakes (optional).',
  },
  {
    id: '8',
    name: 'Suishi',
    price: 10.50,
    delPrice: 2.50,
    category: 'Starters',
    rating: 4.7,
    description: 'Freshly made and authentic Japanese suishi.',
    preparationTime: '15-20 mins',
    deliveryCost: 'Delivery from £2.50',
    image: require('../assets/suishi1.jpg'),
    calories: 350,
    ingredients: 'Sushi rice, nori (seaweed), fresh fish (salmon, tuna, etc.), cucumber, avocado, soy sauce, wasabi, pickled ginger.',
  },
  {
    id: '9',
    name: 'Ramen Noodles',
    price: 8.50,
    delPrice: 1.90,
    category: 'Mains',
    rating: 4.8,
    description: 'Tasty noodles with chicken and vegetables.',
    preparationTime: '15-30 mins',
    deliveryCost: 'Delivery from £1.90',
    image: require('../assets/noodles1.jpg'),
    calories: 190,
    ingredients: 'Ramen noodles, chicken breast, bok choy, mushrooms, carrots, spring onions, soy sauce, sesame oil, garlic, ginger, chicken broth, miso paste (optional).',
  },
  {
    id: '10',
    name: 'French Fries',
    price: 6.99,
    delPrice: 1.20,
    category: 'Starters',
    rating: 4.1,
    description: 'Freshly made potatoe fries with salt and pepper.',
    preparationTime: '10-12 mins',
    deliveryCost: 'Delivery from £1.20',
    image: require('../assets/fries1.jpg'),
    calories: 195,
    ingredients: 'Potatoes, vegetable oil, salt, black pepper, optional seasonings (garlic powder, paprika).',
  },
  {
    id: '11',
    name: 'Chocolate Cake',
    price: 5.99,
    delPrice: 2.30,
    category: 'Desserts',
    rating: 4.9,
    description: 'Sweet chocolate cake topped with biscuits and creame.',
    preparationTime: '15-25 mins',
    deliveryCost: 'Delivery from £2.30',
    image: require('../assets/cake1.jpg'),
    calories: 370,
    ingredients: 'Flour, cocoa powder, sugar, butter, eggs, baking powder, milk, dark chocolate, vanilla extract, heavy cream, biscuits (for topping).',
  },
  {
    id: '12',
    name: 'Garlic Bread',
    price: 3.99,
    delPrice: 1.70,
    category: 'Starters',
    rating: 4.6,
    description: 'Cheesy garlic bread plus sauce of your choice.',
    preparationTime: '10-15 mins',
    deliveryCost: 'Delivery from £1.70',
    image: require('../assets/garlic1.jpg'),
    calories: 350,
    ingredients: 'Bread (baguette or Italian loaf), butter, garlic, parsley, mozzarella cheese, parmesan cheese, optional dipping sauce (marinara, ranch, etc.).',
  },
  {
    id: '13',
    name: 'Pepperoni Pizza',
    price: 13.99,
    delPrice: 1.80,
    category: 'Mains',
    rating: 4.7,
    description: 'A delicious pizza topped with melty mozzarella cheese and spicy pepperoni.',
    preparationTime: '20-35 mins',
    deliveryCost: 'Delivery from £1.80',
    image: require('../assets/pepperoni1.jpg'),
    calories: 270,
    ingredients: 'Pizza dough, crushed tomatoes, garlic powder, onion powder, oregano, basil, mozzarella cheese, pepperoni slices, olive oil.',
  },
  {
    id: '14',
    name: 'Vegetable Pizza',
    price: 11.99,
    delPrice: 1.30,
    category: 'Mains',
    rating: 4.5,
    description: 'A flavorful pizza loaded with fresh vegetables and topped with melty mozzarella cheese.',
    preparationTime: '10-20 mins',
    deliveryCost: 'Delivery from £1.30',
    image: require('../assets/vegpizz1.jpg'),
    calories: 180,
    ingredients: 'Pizza dough, crushed tomatoes, garlic powder, onion powder, oregano, basil, mozzarella cheese, bell peppers, onions, mushrooms, olives, spinach, olive oil.',
  },
  {
    id: '15',
    name: 'Chicken Burger',
    price: 7.99,
    delPrice: 1.20,
    category: 'Mains',
    rating: 4.4,
    description: 'A juicy and flavorful chicken burger served with fresh lettuce, tomato, and your choice of sauce.',
    preparationTime: '15-20 mins',
    deliveryCost: 'Delivery from £1.20',
    image: require('../assets/chickenbur1.jpg'),
    calories: 230,
    ingredients: 'Chicken patty, burger bun, lettuce, tomato, pickles, cheese (optional), mayonnaise or ketchup, olive oil for cooking.',
  },
  {
    id: '16',
    name: 'Strawberry Cake',
    price: 9.99,
    delPrice: 1.40,
    category: 'Desserts',
    rating: 4.9,
    description: 'A light and fluffy cake topped with fresh strawberries and a creamy frosting.',
    preparationTime: '12-15 mins',
    deliveryCost: 'Delivery from £1.40',
    image: require('../assets/strawcake1.jpg'),
    calories: 190,
    ingredients: 'Cake flour, sugar, butter, eggs, vanilla extract, baking powder, milk, fresh strawberries, whipped cream, powdered sugar.',
  },
  {
    id: '17',
    name: 'Vanilla Cake',
    price: 12.99,
    delPrice: 1.20,
    category: 'Desserts',
    rating: 4.8,
    description: 'A soft and moist vanilla cake topped with a smooth, creamy frosting.',
    preparationTime: '10-15 mins',
    deliveryCost: 'Delivery from £1.20',
    image: require('../assets/vancake1.jpg'),
    calories: 300,
    ingredients: 'Cake flour, sugar, butter, eggs, vanilla extract, baking powder, milk, vanilla frosting, powdered sugar.',
  },
  {
    id: '18',
    name: 'Chocolate Milkshake',
    price: 8.99,
    delPrice: 1.30,
    category: 'Desserts',
    rating: 4.7,
    description: 'A rich and creamy chocolate milkshake made with ice cream, milk, and chocolate syrup.',
    preparationTime: '12-15 mins',
    deliveryCost: 'Delivery from £1.30',
    image: require('../assets/chocmilk1.jpg'),
    calories: 450,
    ingredients: 'Chocolate ice cream, milk, chocolate syrup, whipped cream (optional), chocolate shavings (optional).',
  },
  {
    id: '19',
    name: 'Strawberry Milkshake',
    price: 8.99,
    delPrice: 1.20,
    category: 'Desserts',
    rating: 4.6,
    description: 'A creamy and refreshing strawberry milkshake made with ice cream, milk, and fresh strawberries.',
    preparationTime: '12-15 mins',
    deliveryCost: 'Delivery from £1.20',
    image: require('../assets/strawmilk1.jpg'),
    calories: 580,
    ingredients: 'Strawberry ice cream, milk, fresh strawberries, whipped cream (optional), strawberry syrup (optional).',
  },
  {
    id: '20',
    name: 'Vanilla Milkshake',
    price: 8.99,
    delPrice: 1.10,
    category: 'Desserts',
    rating: 4.5,
    description: 'A smooth and creamy vanilla milkshake made with ice cream, milk, and a touch of vanilla flavor.',
    preparationTime: '12-15 mins',
    deliveryCost: 'Delivery from £1.10',
    image: require('../assets/vanmilk1.jpg'),
    calories: 350,
    ingredients: 'Vanilla ice cream, milk, vanilla extract, whipped cream (optional), vanilla syrup (optional).',
  },
  {
    id: '21',
    name: 'Budweiser Beer',
    price: 5.99,
    delPrice: 0.50,
    category: 'Starters',
    rating: 4.5,
    description: 'A refreshing and crisp lager with a smooth finish, perfect for any occasion.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/budbeer1.jpg'),
    calories: 40,
    ingredients: 'Water, barley, rice, hops, yeast.',
  },
  {
    id: '22',
    name: 'Corona Beer',
    price: 5.99,
    delPrice: 0.50,
    category: 'Starters',
    rating: 4.4,
    description: 'A refreshing and crisp lager with a smooth finish, perfect for relaxing and enjoying with friends.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/coronabeer1.jpg'),
    calories: 40,
    ingredients: 'Water, barley, rice, hops, yeast.',
  },
  {
    id: '23',
    name: 'Heineken Beer',
    price: 5.99,
    delPrice: 0.50,
    category: 'Starters',
    rating: 4.6,
    description: 'A refreshing and crisp lager with a smooth, slightly bitter taste, perfect for relaxing with friends.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/heinkbeer1.jpg'),
    calories: 40,
    ingredients: 'Water, barley, hops, yeast.',
  },
  {
    id: '24',
    name: 'Coca Cola',
    price: 2.99,
    delPrice: 0.50,
    category: 'Starters',
    rating: 4.6,
    description: 'A refreshing, sweet carbonated drink, perfect for quenching your thirst and enjoying any meal.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/coke1.jpg'),
    calories: 140,
    ingredients: 'Carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine.',
  },
  {
    id: '25',
    name: 'Fanta',
    price: 2.99,
    delPrice: 0.50,
    category: 'Starters',
    rating: 4.5,
    description: 'A refreshing, sweet and fruity carbonated drink, perfect for quenching your thirst and enjoying any meal.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/fanta1.jpg'),
    calories: 100,
    ingredients: 'Carbonated water, high fructose corn syrup, natural flavors, citric acid, artificial colorings.',
  },
  {
    id: '26',
    name: 'Pepsi',
    price: 2.99,
    delPrice: 0.50,
    category: 'Starters',
    rating: 4.7,
    description: 'A refreshing, sweet and fruity carbonated drink, perfect for quenching your thirst and enjoying any meal.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/pepsi1.jpg'),
    calories: 150,
    ingredients: 'Carbonated water, high fructose corn syrup, natural flavors, citric acid, artificial colorings, caffeine.',
  },
  {
    id: '27',
    name: 'Vanilla Ice Cream',
    price: 3.99,
    delPrice: 0.50,
    category: 'Desserts',
    rating: 4.7,
    description: 'A rich and creamy vanilla ice cream, perfect for dessert or as a sweet treat any time of the day.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/vancream1.jpg'),
    calories: 210,
    ingredients: 'Milk, cream, sugar, vanilla extract, egg yolks (optional).',
  },
  {
    id: '28',
    name: 'Chocolate Ice Cream',
    price: 3.99,
    delPrice: 0.50,
    category: 'Desserts',
    rating: 4.8,
    description: 'A rich and creamy chocolate ice cream, perfect for dessert or as a sweet treat any time of the day.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/choccream1.jpg'),
    calories: 215,
    ingredients: 'Milk, cream, sugar, cocoa powder, vanilla extract, egg yolks (optional).',
  },
  {
    id: '29',
    name: 'Strawberry Ice Cream',
    price: 3.99,
    delPrice: 0.50,
    category: 'Desserts',
    rating: 4.9,
    description: 'A rich and creamy strawberry ice cream, perfect for dessert or as a sweet treat any time of the day.',
    preparationTime: '5-10 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/strawcream1.jpg'),
    calories: 130,
    ingredients: 'Milk, cream, sugar, strawberry puree, vanilla extract, egg yolks (optional).',
  },
  {
    id: '30',
    name: 'Chicken Nuggets',
    price: 4.99,
    delPrice: 0.50,
    category: 'Starters',
    rating: 4.8,
    description: 'Crispy, golden-brown chicken nuggets, perfect for dipping in your favorite sauces.',
    preparationTime: '10-12 mins',
    deliveryCost: 'Delivery from £0.50',
    image: require('../assets/chicknugg1.jpg'),
    calories: 300,
    ingredients: 'Chicken breast, bread crumbs, flour, egg, salt, pepper, vegetable oil for frying.',
  },
];

export default mockMenu;


















